Repository UBC-MDS/DSCI-532_2024_19_food-price-tracker, pull requests merged in 2024-04, with the labels that each got.

#34 Initialize dashboard
  CONTRIBUTING.md
  README.md
  environment.yml
  src/app.py
Labels: enhancement

#44 fix: update the files to prepare for deployment
  environment.yml
  requirements.txt
  src/app.py
Labels: enhancement

#49 feat: implement data fetch and preprocessing
  environment.yml
  requirements.txt
  src/fetch_data.py
Labels: enhancement

#50 feat: app initialization, data loading, widget initialization
  environment.yml
  src/app.py
  src/fetch_data.py
Labels: enhancement

#67 docs: modified the docstring of the functions
  src/app.py
  src/calc_index.py
Labels: documentation

#71 feat: trigger 0.2.0 release for milestone 2 submission
  README.md
Labels: deliverable

#87 62 bugfix chart render sync delay
  src/app.py
Labels: bug, deliverable

#98 75 5 break code into multiple files
  src/app.py
  src/calc_index.py
  src/callbacks.py
  src/data.py
  src/data_preprocess.py
  src/fetch_data.py
Labels: deliverable

#109 fix: match index / commodity chart width
  src/callbacks.py
Labels: bug

#126 fix: performance: remove pd.apply in codebase
  src/data.py
  src/plotting.py
Labels: enhancement, deliverable

#133 feat: implement memoization for country data preprocessing, minor bugfixes
  .gitignore
  environment.yml
  requirements.txt
  src/app.py
  src/cache_config.py
  src/callbacks.py
  src/data.py
  src/utils.py
Labels: bug, enhancement, deliverable
