Repository UBC-MDS/DSCI-532_2024_19_food-price-tracker, pull requests merged in 2024-03, with the labels that each got.

#6 Update repo structure
  .github/workflows/ci-cd.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  data/raw/.EMPTY
  data/raw/wfp_food_prices_jpn.csv
  environment.yml
  img/.EMPTY
  notebooks/.EMPTY
  reports/m1_proposal.md
  src/app.py
Labels: documentation

#19 fix: Remove CI/CD of the python-semantic-release
  .github/workflows/ci-cd.yml
Labels: bug

#21 docs: draft complete for sections 1 and 3 of m1_proposal.md
  reports/m1_proposal.md
Labels: documentation

#22 docs: edit s2 in m1_proposal
  reports/m1_proposal.md
Labels: documentation

#24 docs: edit m1_EDA
  notebooks/m1_EDA.ipynb
Labels: enhancement

#23 Condense and finalize M1 Proposal and README.md
  README.md
  data/raw/.EMPTY
  img/.EMPTY
  img/sketch_basic.jpg
  img/sketch_geo.jpg
  reports/m1_proposal.md
Labels: documentation

#27 feat: manually trigger release
  README.md
Labels: enhancement

#28 Revert "fix: Remove CI/CD of the python-semantic-release"
  .github/workflows/ci-cd.yml
Labels: bug

#29 feat: Update ci-cd.yml for manual release trigger
  .github/workflows/ci-cd.yml
Labels: bug

#30 feat: Update ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: bug
